import FranchiseLead from "../models/FranchiseLead.js";

// ------------------------------------------------------
// 1️⃣ ADD NEW FRANCHISE LEAD
// ------------------------------------------------------
export const addFranchiseLead = async (req, res) => {
  try {
    const { ownerName, ownerEmail, ownerPhone, fullAddress } = req.body;

    if (!ownerName || !ownerEmail || !ownerPhone || !fullAddress) {
      return res.status(400).json({ message: "All fields are required." });
    }

    // managerId comes from auth middleware
    const managerId = req.user.managerId;
    console.log(managerId);

    if (!managerId) {
      return res.status(403).json({ message: "Only managers can add leads." });
    }

    const lead = await FranchiseLead.create({
      ownerName,
      ownerEmail,
      ownerPhone,
      fullAddress,
      managerId,
    });

    return res.status(201).json({
      message: "Franchise Lead created successfully",
      lead,
    });
  } catch (error) {
    console.error("Add Franchise Lead Error:", error);
    return res.status(500).json({ message: "Internal server error" });
  }
};

// ------------------------------------------------------
// 2️⃣ ADD FOLLOW-UP NOTE (date + time + note)
// ------------------------------------------------------

// export const addLeadNote = async (req, res) => {
//   try {
//     const { leadId } = req.params;
//     const { time, note } = req.body;

//     if (!time || !note) {
//       return res.status(400).json({ message: "time and note are required." });
//     }

//     const lead = await FranchiseLead.findById(leadId);

//     if (!lead) {
//       return res.status(404).json({ message: "Lead not found" });
//     }

//     // Only assigned manager can add note
//     if (lead.managerId.toString() !== req.user.managerId) {
//       return res.status(403).json({ message: "Unauthorized" });
//     }

//     // Push follow-up entry
//     lead.notes.push({
//       date: new Date(),
//       time,
//       note,
//     });

//     lead.lastContactedAt = new Date();

//     await lead.save();

//     return res.status(200).json({
//       message: "Follow-up note added successfully",
//       lead,
//     });
//   } catch (error) {
//     console.error("Add Note Error:", error);
//     return res.status(500).json({ message: "Internal server error" });
//   }
// };
export const addLeadNote = async (req, res) => {
  try {
    const { leadId } = req.params;
    const { note } = req.body;

    if (!note) {
      return res.status(400).json({ message: "note is required." });
    }

    const lead = await FranchiseLead.findById(leadId);

    if (!lead) {
      return res.status(404).json({ message: "Lead not found" });
    }

    // Only assigned manager can add note
    if (lead.managerId.toString() !== req.user.managerId) {
      return res.status(403).json({ message: "Unauthorized" });
    }

    // Generate server time
    const now = new Date();
    const formattedTime = now.toLocaleTimeString("en-IN", {
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      hour12: true,
    });

    // Push follow-up entry
    lead.notes.push({
      date: now,
      time: formattedTime, // auto-generated by backend
      note,
    });

    await lead.save();

    return res.status(200).json({
      message: "Follow-up note added successfully",
      lead,
    });
  } catch (error) {
    console.error("Add Note Error:", error);
    return res.status(500).json({ message: "Internal server error" });
  }
};

// ------------------------------------------------------
// 3️⃣ UPDATE LEAD STATUS
// ------------------------------------------------------
export const updateLeadStatus = async (req, res) => {
  try {
    const { leadId } = req.params;
    const { status } = req.body;

    const allowed = [
      "New",
      "In Progress",
      "Interested",
      "Not Interested",
      "Closed",
    ];

    if (!allowed.includes(status)) {
      return res.status(400).json({ message: "Invalid status" });
    }

    const lead = await FranchiseLead.findById(leadId);

    if (!lead) return res.status(404).json({ message: "Lead not found" });

    // Only assigned manager
    if (lead.managerId.toString() !== req.user.managerId) {
      return res.status(403).json({ message: "Unauthorized" });
    }

    lead.status = status;
    await lead.save();

    return res.status(200).json({ message: "Status updated", lead });
  } catch (error) {
    console.error("Update Status Error:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};

// ------------------------------------------------------
// 4️⃣ GET LEADS FOR MANAGER (with filters + pagination)
// ------------------------------------------------------
export const getManagerLeads = async (req, res) => {
  try {
    const managerId = req.user.managerId;

    const { status, search, page = 1, limit = 10 } = req.query;

    let filter = { managerId };

    if (status) {
      filter.status = status;
    }

    if (search) {
      filter.$or = [
        { ownerName: new RegExp(search, "i") },
        { ownerEmail: new RegExp(search, "i") },
        { ownerPhone: new RegExp(search, "i") },
      ];
    }

    const skip = (page - 1) * limit;

    const leads = await FranchiseLead.find(filter)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(Number(limit));

    const total = await FranchiseLead.countDocuments(filter);

    return res.status(200).json({
      leads,
      pagination: {
        total,
        page: Number(page),
        limit: Number(limit),
        totalPages: Math.ceil(total / limit),
      },
    });
  } catch (error) {
    console.error("Get Leads Error:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};

// ------------------------------------------------------
// 5️⃣ GET SINGLE LEAD
// ------------------------------------------------------
export const getLeadById = async (req, res) => {
  try {
    const { leadId } = req.params;

    const lead = await FranchiseLead.findById(leadId);

    if (!lead) return res.status(404).json({ message: "Lead not found" });

    return res.status(200).json({ lead });
  } catch (error) {
    console.error("Get Lead Error:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};

// ------------------------------------------------------
// 6️⃣ DELETE LEAD (optional)
// ------------------------------------------------------
export const deleteLead = async (req, res) => {
  try {
    const { leadId } = req.params;

    await FranchiseLead.findByIdAndDelete(leadId);

    return res.status(200).json({ message: "Lead deleted" });
  } catch (error) {
    console.error("Delete Lead Error:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};
